name: CI/CD Pipeline Docker

# 1. Când să ruleze? (Trigger)
on:
  push:
    branches: [ "main" ]

# 2. Ce să facă? (Jobs)
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install flask
      - name: Run Tests
        run: python test_app.py

  build-and-push:

    needs: test  # <--- ASTA E CHEIA! Nu incepe fara ca 'test' sa fie verde.
    runs-on: ubuntu-latest  # GitHub ne împrumută un server Ubuntu

    steps:
      # Pasul A: Descarcă codul tău pe serverul GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Pasul B: Se loghează în Docker Hub (folosind secretele)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pasul C: Construiește și urcă imaginea
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Aici folosim variabila speciala pentru a pune tag-ul 'latest'
          tags: ${{ secrets.DOCKER_USERNAME }}/proiect-devops-invatare:latest
