name: CI/CD Pipeline Docker

# 1. Când să ruleze? (Trigger)
on:
  push:
    branches: [ "main" ]

# 2. Ce să facă? (Jobs)
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub ne împrumută un server Ubuntu

    steps:
      # Pasul A: Descarcă codul tău pe serverul GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Pasul B: Se loghează în Docker Hub (folosind secretele)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pasul C: Construiește și urcă imaginea
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Aici folosim variabila speciala pentru a pune tag-ul 'latest'
          tags: ${{ secrets.DOCKER_USERNAME }}/proiect-devops-invatare:latest
