name: CI/CD Pipeline Avansat

# 1. Trigger: Când pornește?
# Pornește la orice push pe 'main' sau pe 'develop'
# ȘI pornește când pui un tag nou de git (ex: v1.0)
on:
  push:
    branches: 
      - main
      - develop
    tags:
      - 'v*'

jobs:
  # Job 1: Testarea Automată
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descarcă Codul
        uses: actions/checkout@v4

      - name: Pregătește Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalează Dependințe
        run: pip install flask

      - name: Rulează Testele
        run: python test_app.py

  # Job 2: Build și Push (rulează DOAR dacă testele au trecut)
  build-and-push:
    needs: test  # Așteaptă verde de la test
    runs-on: ubuntu-latest
    
    # Definim permisiuni pentru a citi repo-ul
    permissions:
      contents: read
      packages: write

    steps:
      - name: Descarcă Codul
        uses: actions/checkout@v4

      # Logare în Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pasul MAGIC: Generarea Tag-urilor
      # Aici Docker decide ce nume va avea imaginea
      - name: Docker Meta (Generare Tag-uri)
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Inlocuieste cu imaginea ta reala!
          images: valentin3005/proiect-devops-invatare
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=beta,enable=${{ github.ref == 'refs/heads/develop' }}
            type=ref,event=tag


      # Construcția și Upload-ul
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Folosim tag-urile generate automat mai sus
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
